---
name: build

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# (none)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  # Build daily at 6:02am...
  - cron: '2 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r build-requirements.txt
        pip install -r package-requirements.txt
    - name: Test
      run: |
        pyroma .
        pylint dm_job_utilities
        mypy dm_job_utilities --install-types --non-interactive
    - name: Build
      run: |
        python setup.py bdist_wheel
